# Generated by Django 3.1.7 on 2021-03-03 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='Types',
        ),
    ]
